services:
  scheduler:
    image: ghcr.io/casparemiljensen/aau-parking-permit:latest
    container_name: parking-scheduler
    restart: always
    environment:
      - TZ=Europe/Copenhagen
    volumes:
      - ./data:/app/data:rw