name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx (optional for multi-platform support)
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.aau-parking-permit-ghcr }}

    - name: Build the Docker image
      run: |
        IMAGE_TAG=aau-parking-permit:${{ github.sha }}
        docker build . --file Dockerfile --tag $IMAGE_TAG

    - name: Push the Docker image
      run: |
        IMAGE_TAG=aau-parking-permit:${{ github.sha }}
        docker push $IMAGE_TAG
